### ISSUE TITLE
"Auto-pronounce words in main window" not work

### ISSUE THREAD

**Issue by playgithub** [xiaoyifang/goldendict-ng#1396]
### Version
* GoldenDict 24.01.22
* OS archlinux 20204.2.5
* Desktop KDE Plasma 5.27
* Dict 牛津高阶英汉双解词典（简体）第8版

### Problem
* "Auto-pronounce words in main window" not work

### Others
No problem for Qt 6.7 on Windows 11

**Comment by KonstantinDjairo** [comment]
i had the same problem , they don't work to me

**Comment by xiaoyifang** [comment]
Need more information:
1. manually play the **first** sound?  does it work?
2. change the audio engine to external player, does it work?

**Comment by playgithub** [comment]
> 1. manually play the **first** sound?  does it work?

Yes

> 2. change the audio engine to external player or ffmpeg, does it work?

No

**Comment by xiaoyifang** [comment]
I guess the first found audio file by the gd-ng maybe broken.

**Comment by playgithub** [comment]
When using only one dict ("Dict 牛津高阶英汉双解词典（简体）第8版"), the problem still exists.

**Comment by KonstantinDjairo** [comment]
> > 1. manually play the **first** sound?  does it work?
> 
> Yes
> 
> > 2. change the audio engine to external player or ffmpeg, does it work?
> 
> No

 exactly the same here.

**Comment by JingMatrix** [comment]
To solve this problem, create a file `article-script.js` with the following content
```js
window.addEventListener("load", () => {
  setTimeout(() => {
    window.location.href = gdAudioLinks.first;
  }, 0);   
});
```
and then put into the `~/.goldendict` folder.

**Comment by playgithub** [comment]
> To solve this problem, create a file `article-script.js` with the following content
> 
> ```js
> window.addEventListener("load", () => {
>   setTimeout(() => {
>     window.location.href = gdAudioLinks.first;
>   }, 0);   
> });
> ```
> 
> and then put into the `~/.goldendict` folder.

I've put it in `~/.config/goldendict`, and it works.
However, before the audio playing, it takes a longer latency than when translating from clipboard (Ctrl+C, C).

**Comment by JingMatrix** [comment]
The lag depends on your size of dictionaries, if you want to speed up, then you can try to change the time of wait (which is `300` is the example) before `goldendict` is ready to pronounce:
```js
setTimeout(() => {
  window.location.href = gdAudioLinks.first;
}, 300);
```
And replace your file with the content above.
Warning: **too small** will stop `goldendict` from working properly.

**Comment by playgithub** [comment]
Another problem is that when translating from clipboard (Ctrl+C, C) it'll pronounce twice.

**Comment by JingMatrix** [comment]
> Another problem is that when translating from clipboard (Ctrl+C, C) it'll pronounce twice.

I cannot reproduce it on my device. Maybe it is because that I setup the shortcut in my `sway` config instead of relying on `goldendict` to register a global one.

**Comment by playgithub** [comment]
In my practice, `article-script.js` is works regardless of the options below:
* Auto-pronounce words in main window
* Auto-pronounce words in scan popup

It just add an extra auto-pronounce.

**Comment by JingMatrix** [comment]
Yes, exactly. Please this turn them off.

**Comment by TheNicker** [comment]
@JingMatrix , thanks for the fix

I Had to modify the script in case no audio is found:

```
window.addEventListener("load", () => {
    setTimeout(() => 
    {
      if (gdAudioLinks.first)
        window.location.href = gdAudioLinks.first;
    }, 0);   
  });        
```

**Comment by laraws** [comment]
> To solve this problem, create a file `article-script.js` with the following content
> 
> ```js
> window.addEventListener("load", () => {
>   setTimeout(() => {
>     window.location.href = gdAudioLinks.first;
>   }, 0);   
> });
> ```
> 
> and then put into the `~/.goldendict` folder.

I tried this method, but it didn't work in my app. I installed the Flatpak version running on Ubuntu 22.04.

**Comment by laraws** [comment]
> Need more information:
> 
> 1. manually play the **first** sound?  does it work?
yes
> 2. change the audio engine to external player or ffmpeg, does it work?
no

**Comment by laraws** [comment]
> > To solve this problem, create a file `article-script.js` with the following content
> > ```js
> > window.addEventListener("load", () => {
> >   setTimeout(() => {
> >     window.location.href = gdAudioLinks.first;
> >   }, 0);   
> > });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then put into the `~/.goldendict` folder.
> 
> I tried this method, but it didn't work in my app. I installed the Flatpak version running on Ubuntu 22.04.

It works. I found that the config file for the Flatpak version is located in `~/.var/app/io.github.xiaoyifang.goldendict_ng/config/goldendict.`. Thank you so much.

**Comment by playgithub** [comment]
It is solved offically.

**Comment by laraws** [comment]
> It is solved offically.

I’m using the latest Flatpak version of this app. The version is `24.09.0.316ec90, released on 2024-09-13T13:24:05Z`. I found it still had this problem.

**Comment by shenlebantongying** [comment]
No, it is not solved. The `runJavascript` has documented undefined behavior when the DOM is not fully constructed. It works for small number of dicts accidentally.

> https://doc.qt.io/qt-6/qwebenginepage.html#runJavaScript
> "without checking whether the DOM of the page has been constructed"

https://github.com/xiaoyifang/goldendict-ng/blob/ccbf8b7e5545ba0f874dc1b12f986941af0c789d/src/ui/articleview.cc#L1439

**Comment by xiaoyifang** [comment]
A possible solution is  using Signal/Slot .
When the first audio link found, emit a signal ,the active articleview receive the signal and save the audio link and play the audio (if configured auto-pronounce)

**Comment by laraws** [comment]
> ![image](https://private-user-images.githubusercontent.com/105986/378068541-ff9922fc-76e3-4c4b-9e53-aaa0b9fbfdb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzQ0MjMsIm5iZiI6MTcyOTMzNDEyMywicGF0aCI6Ii8xMDU5ODYvMzc4MDY4NTQxLWZmOTkyMmZjLTc2ZTMtNGM0Yi05ZTUzLWFhYTBiOWZiZmRiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDM1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDAwNTdiYmZiNGM1MjQ3MmNiYWJiNWFmNzI2NGVhNTJiNzk3MzFlNDFhYTY0YzYyN2IyYTA5YzVhYzdjZTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VXTQO3f72Opu36SQ22BB01dQzLBqYpKf3NSEIMxoEp0)
> 
> check whether these options turned on.

My switches are open, but they don't work unless I create a previously mentioned JS file.

```js
window.addEventListener("load", () => {
  setTimeout(() => {
    window.location.href = gdAudioLinks.first;
  }, 0);   
});
```

It is really helpful.
